//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCMVC.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations; //dùng để định nghĩa chú thích cho các trường thuộc tính, bao gồm định nghĩa lại tên hiển thị, kiểu dữ liệu, định dạng dữ liệu hiển thị.

    public partial class Link
    {
        public int LinkID { get; set; }
        [Display(Name = "Tên liên kết")]
        [Required]
        public string LinkName { get; set; }
        public string LinkURL { get; set; }
        public string LinkDescription { get; set; }
        public Nullable<int> CategoryID { get; set; }
    }
}
